version: "3.8"
services:
  backend:
    image: 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:latest
    container_name: performace-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mgid
    networks:
      - performace-net

  mgid:
    image: 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:mgid-crawler-${SHORT_SHA}
    container_name: performace-mgid
    ports:
      - "8001:8001"
    environment:
      - tmp=/tmp
    networks:
      - performace-net

networks:
  performace-net:
    driver: bridge
