FROM node:18-alpine

# Install http-server globally
RUN npm install -g http-server

# Set the working directory in the container
WORKDIR /PerformAce-Dashboard/Frontend

# Copy all HTML and static files to the working directory
COPY . .

# Expose port 80 to allow access
EXPOSE 80

# Use http-server to serve the files
ENTRYPOINT ["Frontend/http-server", "-p", "80", "-a", "0.0.0.0"]
