name: Backend Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4          
      - name: Create .env file
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env          
          echo "PORT=${{ secrets.PORT }}" >> .env   
          echo "TABOOLA_API_BASE_URL=${{ secrets.TABOOLA_API_BASE_URL }}" >> .env
          echo "TABOOLA_AUTH_URL=${{ secrets.TABOOLA_AUTH_URL }}" >> .env   
          echo "TABOOLA_CLIENT_ID=${{ secrets.TABOOLA_CLIENT_ID }}" >> .env
          echo "TABOOLA_CLIENT_SECRET=${{ secrets.TABOOLA_CLIENT_SECRET}}" >> .env  
          echo "TABOOLA_ACCOUNT_ID=${{ secrets.TABOOLA_ACCOUNT_ID}}" >> .env  
          echo "JWT_SECRET=${{ secrets.JWT_SECRET}}" >> .env  
          
      - name: Display .env file
        run: cat .env      
      - name: Build docker -t
        run: docker build -f Dockerfile -t 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:latest .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 209479285380.dkr.ecr.ap-south-1.amazonaws.com
      - name: Publish image to docker hub
        run: docker push 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:latest          
      - name: Load .env file
        uses: dotenv-linter/action-dotenv-linter@v1
        with:
         env_path: .env
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 209479285380.dkr.ecr.ap-south-1.amazonaws.com          
      - name: Pull Docker image
        run: docker pull 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:latest 
      - name: Delete old container
        run: docker rm -f performace-backend     
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name performace-backend 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:latest
