name: Deploy Nodejs Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4               
      - name: Build docker -t
        run: docker build -f Dockerfile_Frontend -t 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:frontend-${{ github.sha }} .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 209479285380.dkr.ecr.ap-south-1.amazonaws.com
      - name: Publish image to docker hub
        run: docker push 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:frontend-${{ github.sha }}

        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 209479285380.dkr.ecr.ap-south-1.amazonaws.com          
      - name: Pull Docker image
        run: docker pull 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:frontend-${{ github.sha }}
      - name: Delete old container
        run: docker rm -f performace-frontend     
      - name: Run docker container
        run: docker run -d -p 80:80 --name performace-frontend 209479285380.dkr.ecr.ap-south-1.amazonaws.com/performace-dashboard:frontend-${{ github.sha }}
